[package]
name = "ft-yoshi"
description = "Yoshi character data and callbacks (ftYoshi)"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
melee-types = { path = "../melee-types" }
melee-ft = { path = "../melee-ft" }
hsd-types = { path = "../hsd-types" }
hsd-archive = { path = "../hsd-archive" }
gekko-math = { path = "../gekko-math" }
