[package]
name = "ft-ganon"
description = "Ganondorf character data and callbacks (ftGanon)"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ft-captain-family = { path = "../ft-captain-family" }
melee-types = { path = "../melee-types" }
melee-ft = { path = "../melee-ft" }
melee-lb = { path = "../melee-lb" }
hsd-archive = { path = "../hsd-archive" }
hsd-types = { path = "../hsd-types" }
gekko-math = { path = "../gekko-math" }

[dev-dependencies]
melee-test-support = { path = "../melee-test-support" }
