//! ftData_MotionStateList (ftmotionstates.c): names in retail table-index order.
use super::COMMON_COUNT;

pub(super) const COMMON_NAMES: [&str; COMMON_COUNT] = [
    "ftCo_MS_DeadDown",                // 0
    "ftCo_MS_DeadLeft",                // 1
    "ftCo_MS_DeadRight",               // 2
    "ftCo_MS_DeadUp",                  // 3
    "ftCo_MS_DeadUpStar",              // 4
    "ftCo_MS_DeadUpStarIce",           // 5
    "ftCo_MS_DeadUpFall",              // 6
    "ftCo_MS_DeadUpFallHitCamera",     // 7
    "ftCo_MS_DeadUpFallHitCameraFlat", // 8
    "ftCo_MS_DeadUpFallIce",           // 9
    "ftCo_MS_DeadUpFallHitCameraIce",  // 10
    "ftCo_MS_Sleep",                   // 11
    "ftCo_MS_Rebirth",                 // 12
    "ftCo_MS_RebirthWait",             // 13
    "ftCo_MS_Wait",                    // 14
    "ftCo_MS_WalkSlow",                // 15
    "ftCo_MS_WalkMiddle",              // 16
    "ftCo_MS_WalkFast",                // 17
    "ftCo_MS_Turn",                    // 18
    "ftCo_MS_TurnRun",                 // 19
    "ftCo_MS_Dash",                    // 20
    "ftCo_MS_Run",                     // 21
    "ftCo_MS_RunDirect",               // 22
    "ftCo_MS_RunBrake",                // 23
    "ftCo_MS_KneeBend",                // 24
    "ftCo_MS_JumpF",                   // 25
    "ftCo_MS_JumpB",                   // 26
    "ftCo_MS_JumpAerialF",             // 27
    "ftCo_MS_JumpAerialB",             // 28
    "ftCo_MS_Fall",                    // 29
    "ftCo_MS_FallF",                   // 30
    "ftCo_MS_FallB",                   // 31
    "ftCo_MS_FallAerial",              // 32
    "ftCo_MS_FallAerialF",             // 33
    "ftCo_MS_FallAerialB",             // 34
    "ftCo_MS_FallSpecial",             // 35
    "ftCo_MS_FallSpecialF",            // 36
    "ftCo_MS_FallSpecialB",            // 37
    "ftCo_MS_DamageFall",              // 38
    "ftCo_MS_Squat",                   // 39
    "ftCo_MS_SquatWait",               // 40
    "ftCo_MS_SquatRv",                 // 41
    "ftCo_MS_Landing",                 // 42
    "ftCo_MS_LandingFallSpecial",      // 43
    "ftCo_MS_Attack11",                // 44
    "ftCo_MS_Attack12",                // 45
    "ftCo_MS_Attack13",                // 46
    "ftCo_MS_Attack100Start",          // 47
    "ftCo_MS_Attack100Loop",           // 48
    "ftCo_MS_Attack100End",            // 49
    "ftCo_MS_AttackDash",              // 50
    "ftCo_MS_AttackS3Hi",              // 51
    "ftCo_MS_AttackS3HiS",             // 52
    "ftCo_MS_AttackS3S",               // 53
    "ftCo_MS_AttackS3LwS",             // 54
    "ftCo_MS_AttackS3Lw",              // 55
    "ftCo_MS_AttackHi3",               // 56
    "ftCo_MS_AttackLw3",               // 57
    "ftCo_MS_AttackS4Hi",              // 58
    "ftCo_MS_AttackS4HiS",             // 59
    "ftCo_MS_AttackS4S",               // 60
    "ftCo_MS_AttackS4LwS",             // 61
    "ftCo_MS_AttackS4Lw",              // 62
    "ftCo_MS_AttackHi4",               // 63
    "ftCo_MS_AttackLw4",               // 64
    "ftCo_MS_AttackAirN",              // 65
    "ftCo_MS_AttackAirF",              // 66
    "ftCo_MS_AttackAirB",              // 67
    "ftCo_MS_AttackAirHi",             // 68
    "ftCo_MS_AttackAirLw",             // 69
    "ftCo_MS_LandingAirN",             // 70
    "ftCo_MS_LandingAirF",             // 71
    "ftCo_MS_LandingAirB",             // 72
    "ftCo_MS_LandingAirHi",            // 73
    "ftCo_MS_LandingAirLw",            // 74
    "ftCo_MS_DamageHi1",               // 75
    "ftCo_MS_DamageHi2",               // 76
    "ftCo_MS_DamageHi3",               // 77
    "ftCo_MS_DamageN1",                // 78
    "ftCo_MS_DamageN2",                // 79
    "ftCo_MS_DamageN3",                // 80
    "ftCo_MS_DamageLw1",               // 81
    "ftCo_MS_DamageLw2",               // 82
    "ftCo_MS_DamageLw3",               // 83
    "ftCo_MS_DamageAir1",              // 84
    "ftCo_MS_DamageAir2",              // 85
    "ftCo_MS_DamageAir3",              // 86
    "ftCo_MS_DamageFlyHi",             // 87
    "ftCo_MS_DamageFlyN",              // 88
    "ftCo_MS_DamageFlyLw",             // 89
    "ftCo_MS_DamageFlyTop",            // 90
    "ftCo_MS_DamageFlyRoll",           // 91
    "ftCo_MS_LightGet",                // 92
    "ftCo_MS_HeavyGet",                // 93
    "ftCo_MS_LightThrowF",             // 94
    "ftCo_MS_LightThrowB",             // 95
    "ftCo_MS_LightThrowHi",            // 96
    "ftCo_MS_LightThrowLw",            // 97
    "ftCo_MS_LightThrowDash",          // 98
    "ftCo_MS_LightThrowDrop",          // 99
    "ftCo_MS_LightThrowAirF",          // 100
    "ftCo_MS_LightThrowAirB",          // 101
    "ftCo_MS_LightThrowAirHi",         // 102
    "ftCo_MS_LightThrowAirLw",         // 103
    "ftCo_MS_HeavyThrowF",             // 104
    "ftCo_MS_HeavyThrowB",             // 105
    "ftCo_MS_HeavyThrowHi",            // 106
    "ftCo_MS_HeavyThrowLw",            // 107
    "ftCo_MS_LightThrowF4",            // 108
    "ftCo_MS_LightThrowB4",            // 109
    "ftCo_MS_LightThrowHi4",           // 110
    "ftCo_MS_LightThrowLw4",           // 111
    "ftCo_MS_LightThrowAirF4",         // 112
    "ftCo_MS_LightThrowAirB4",         // 113
    "ftCo_MS_LightThrowAirHi4",        // 114
    "ftCo_MS_LightThrowAirLw4",        // 115
    "ftCo_MS_HeavyThrowF4",            // 116
    "ftCo_MS_HeavyThrowB4",            // 117
    "ftCo_MS_HeavyThrowHi4",           // 118
    "ftCo_MS_HeavyThrowLw4",           // 119
    "ftCo_MS_SwordSwing1",             // 120
    "ftCo_MS_SwordSwing3",             // 121
    "ftCo_MS_SwordSwing4",             // 122
    "ftCo_MS_SwordSwingDash",          // 123
    "ftCo_MS_BatSwing1",               // 124
    "ftCo_MS_BatSwing3",               // 125
    "ftCo_MS_BatSwing4",               // 126
    "ftCo_MS_BatSwingDash",            // 127
    "ftCo_MS_ParasolSwing1",           // 128
    "ftCo_MS_ParasolSwing3",           // 129
    "ftCo_MS_ParasolSwing4",           // 130
    "ftCo_MS_ParasolSwingDash",        // 131
    "ftCo_MS_HarisenSwing1",           // 132
    "ftCo_MS_HarisenSwing3",           // 133
    "ftCo_MS_HarisenSwing4",           // 134
    "ftCo_MS_HarisenSwingDash",        // 135
    "ftCo_MS_StarRodSwing1",           // 136
    "ftCo_MS_StarRodSwing3",           // 137
    "ftCo_MS_StarRodSwing4",           // 138
    "ftCo_MS_StarRodSwingDash",        // 139
    "ftCo_MS_LipstickSwing1",          // 140
    "ftCo_MS_LipstickSwing3",          // 141
    "ftCo_MS_LipstickSwing4",          // 142
    "ftCo_MS_LipstickSwingDash",       // 143
    "ftCo_MS_ItemParasolOpen",         // 144
    "ftCo_MS_ItemParasolFall",         // 145
    "ftCo_MS_ItemParasolFallSpecial",  // 146
    "ftCo_MS_ItemParasolDamageFall",   // 147
    "ftCo_MS_LGunShoot",               // 148
    "ftCo_MS_LGunShootAir",            // 149
    "ftCo_MS_LGunShootEmpty",          // 150
    "ftCo_MS_LGunShootAirEmpty",       // 151
    "ftCo_MS_FireFlowerShoot",         // 152
    "ftCo_MS_FireFlowerShootAir",      // 153
    "ftCo_MS_ItemScrew",               // 154
    "ftCo_MS_ItemScrewAir",            // 155
    "ftCo_MS_DamageScrew",             // 156
    "ftCo_MS_DamageScrewAir",          // 157
    "ftCo_MS_ItemScopeStart",          // 158
    "ftCo_MS_ItemScopeRapid",          // 159
    "ftCo_MS_ItemScopeFire",           // 160
    "ftCo_MS_ItemScopeEnd",            // 161
    "ftCo_MS_ItemScopeAirStart",       // 162
    "ftCo_MS_ItemScopeAirRapid",       // 163
    "ftCo_MS_ItemScopeAirFire",        // 164
    "ftCo_MS_ItemScopeAirEnd",         // 165
    "ftCo_MS_ItemScopeStartEmpty",     // 166
    "ftCo_MS_ItemScopeRapidEmpty",     // 167
    "ftCo_MS_ItemScopeFireEmpty",      // 168
    "ftCo_MS_ItemScopeEndEmpty",       // 169
    "ftCo_MS_ItemScopeAirStartEmpty",  // 170
    "ftCo_MS_ItemScopeAirRapidEmpty",  // 171
    "ftCo_MS_ItemScopeAirFireEmpty",   // 172
    "ftCo_MS_ItemScopeAirEndEmpty",    // 173
    "ftCo_MS_LiftWait",                // 174
    "ftCo_MS_LiftWalk1",               // 175
    "ftCo_MS_LiftWalk2",               // 176
    "ftCo_MS_LiftTurn",                // 177
    "ftCo_MS_GuardOn",                 // 178
    "ftCo_MS_Guard",                   // 179
    "ftCo_MS_GuardOff",                // 180
    "ftCo_MS_GuardSetOff",             // 181
    "ftCo_MS_GuardReflect",            // 182
    "ftCo_MS_DownBoundU",              // 183
    "ftCo_MS_DownWaitU",               // 184
    "ftCo_MS_DownDamageU",             // 185
    "ftCo_MS_DownStandU",              // 186
    "ftCo_MS_DownAttackU",             // 187
    "ftCo_MS_DownFowardU",             // 188
    "ftCo_MS_DownBackU",               // 189
    "ftCo_MS_DownSpotU",               // 190
    "ftCo_MS_DownBoundD",              // 191
    "ftCo_MS_DownWaitD",               // 192
    "ftCo_MS_DownDamageD",             // 193
    "ftCo_MS_DownStandD",              // 194
    "ftCo_MS_DownAttackD",             // 195
    "ftCo_MS_DownFowardD",             // 196
    "ftCo_MS_DownBackD",               // 197
    "ftCo_MS_DownSpotD",               // 198
    "ftCo_MS_Passive",                 // 199
    "ftCo_MS_PassiveStandF",           // 200
    "ftCo_MS_PassiveStandB",           // 201
    "ftCo_MS_PassiveWall",             // 202
    "ftCo_MS_PassiveWallJump",         // 203
    "ftCo_MS_PassiveCeil",             // 204
    "ftCo_MS_ShieldBreakFly",          // 205
    "ftCo_MS_ShieldBreakFall",         // 206
    "ftCo_MS_ShieldBreakDownU",        // 207
    "ftCo_MS_ShieldBreakDownD",        // 208
    "ftCo_MS_ShieldBreakStandU",       // 209
    "ftCo_MS_ShieldBreakStandD",       // 210
    "ftCo_MS_Furafura",                // 211
    "ftCo_MS_Catch",                   // 212
    "ftCo_MS_CatchPull",               // 213
    "ftCo_MS_CatchDash",               // 214
    "ftCo_MS_CatchDashPull",           // 215
    "ftCo_MS_CatchWait",               // 216
    "ftCo_MS_CatchAttack",             // 217
    "ftCo_MS_CatchCut",                // 218
    "ftCo_MS_ThrowF",                  // 219
    "ftCo_MS_ThrowB",                  // 220
    "ftCo_MS_ThrowHi",                 // 221
    "ftCo_MS_ThrowLw",                 // 222
    "ftCo_MS_CapturePulledHi",         // 223
    "ftCo_MS_CaptureWaitHi",           // 224
    "ftCo_MS_CaptureDamageHi",         // 225
    "ftCo_MS_CapturePulledLw",         // 226
    "ftCo_MS_CaptureWaitLw",           // 227
    "ftCo_MS_CaptureDamageLw",         // 228
    "ftCo_MS_CaptureCut",              // 229
    "ftCo_MS_CaptureJump",             // 230
    "ftCo_MS_CaptureNeck",             // 231
    "ftCo_MS_CaptureFoot",             // 232
    "ftCo_MS_EscapeF",                 // 233
    "ftCo_MS_EscapeB",                 // 234
    "ftCo_MS_EscapeN",                 // 235
    "ftCo_MS_EscapeAir",               // 236
    "ftCo_MS_ReboundStop",             // 237
    "ftCo_MS_Rebound",                 // 238
    "ftCo_MS_ThrownF",                 // 239
    "ftCo_MS_ThrownB",                 // 240
    "ftCo_MS_ThrownHi",                // 241
    "ftCo_MS_ThrownLw",                // 242
    "ftCo_MS_ThrownlwWomen",           // 243
    "ftCo_MS_Pass",                    // 244
    "ftCo_MS_Ottotto",                 // 245
    "ftCo_MS_OttottoWait",             // 246
    "ftCo_MS_FlyReflectWall",          // 247
    "ftCo_MS_FlyReflectCeil",          // 248
    "ftCo_MS_StopWall",                // 249
    "ftCo_MS_StopCeil",                // 250
    "ftCo_MS_MissFoot",                // 251
    "ftCo_MS_CliffCatch",              // 252
    "ftCo_MS_CliffWait",               // 253
    "ftCo_MS_CliffClimbSlow",          // 254
    "ftCo_MS_CliffClimbQuick",         // 255
    "ftCo_MS_CliffAttackSlow",         // 256
    "ftCo_MS_CliffAttackQuick",        // 257
    "ftCo_MS_CliffEscapeSlow",         // 258
    "ftCo_MS_CliffEscapeQuick",        // 259
    "ftCo_MS_CliffJumpSlow1",          // 260
    "ftCo_MS_CliffJumpSlow2",          // 261
    "ftCo_MS_CliffJumpQuick1",         // 262
    "ftCo_MS_CliffJumpQuick2",         // 263
    "ftCo_MS_AppealSR",                // 264
    "ftCo_MS_AppealSL",                // 265
    "ftCo_MS_ShoulderedWait",          // 266
    "ftCo_MS_ShoulderedWalkSlow",      // 267
    "ftCo_MS_ShoulderedWalkMiddle",    // 268
    "ftCo_MS_ShoulderedWalkFast",      // 269
    "ftCo_MS_ShoulderedTurn",          // 270
    "ftCo_MS_ThrownFF",                // 271
    "ftCo_MS_ThrownFB",                // 272
    "ftCo_MS_ThrownFHi",               // 273
    "ftCo_MS_ThrownFLw",               // 274
    "ftCo_MS_CaptureCaptain",          // 275
    "ftCo_MS_CaptureYoshi",            // 276
    "ftCo_MS_YoshiEgg",                // 277
    "ftCo_MS_CaptureKoopa",            // 278
    "ftCo_MS_CaptureDamageKoopa",      // 279
    "ftCo_MS_CaptureWaitKoopa",        // 280
    "ftCo_MS_ThrownKoopaF",            // 281
    "ftCo_MS_ThrownKoopaB",            // 282
    "ftCo_MS_CaptureKoopaAir",         // 283
    "ftCo_MS_CaptureDamageKoopaAir",   // 284
    "ftCo_MS_CaptureWaitKoopaAir",     // 285
    "ftCo_MS_ThrownKoopaAirF",         // 286
    "ftCo_MS_ThrownKoopaAirB",         // 287
    "ftCo_MS_CaptureKirby",            // 288
    "ftCo_MS_CaptureWaitKirby",        // 289
    "ftCo_MS_ThrownKirbyStar",         // 290
    "ftCo_MS_ThrownCopyStar",          // 291
    "ftCo_MS_ThrownKirby",             // 292
    "ftCo_MS_BarrelWait",              // 293
    "ftCo_MS_Bury",                    // 294
    "ftCo_MS_BuryWait",                // 295
    "ftCo_MS_BuryJump",                // 296
    "ftCo_MS_DamageSong",              // 297
    "ftCo_MS_DamageSongWait",          // 298
    "ftCo_MS_DamageSongRv",            // 299
    "ftCo_MS_DamageBind",              // 300
    "ftCo_MS_CaptureMewtwo",           // 301
    "ftCo_MS_CaptureMewtwoAir",        // 302
    "ftCo_MS_ThrownMewtwo",            // 303
    "ftCo_MS_ThrownMewtwoAir",         // 304
    "ftCo_MS_WarpStarJump",            // 305
    "ftCo_MS_WarpStarFall",            // 306
    "ftCo_MS_HammerWait",              // 307
    "ftCo_MS_HammerWalk",              // 308
    "ftCo_MS_HammerTurn",              // 309
    "ftCo_MS_HammerKneeBend",          // 310
    "ftCo_MS_HammerFall",              // 311
    "ftCo_MS_HammerJump",              // 312
    "ftCo_MS_HammerLanding",           // 313
    "ftCo_MS_KinokoGiantStart",        // 314
    "ftCo_MS_KinokoGiantStartAir",     // 315
    "ftCo_MS_KinokoGiantEnd",          // 316
    "ftCo_MS_KinokoGiantEndAir",       // 317
    "ftCo_MS_KinokoSmallStart",        // 318
    "ftCo_MS_KinokoSmallStartAir",     // 319
    "ftCo_MS_KinokoSmallEnd",          // 320
    "ftCo_MS_KinokoSmallEndAir",       // 321
    "ftCo_MS_Entry",                   // 322
    "ftCo_MS_EntryStart",              // 323
    "ftCo_MS_EntryEnd",                // 324
    "ftCo_MS_DamageIce",               // 325
    "ftCo_MS_DamageIceJump",           // 326
    "ftCo_MS_CaptureMasterHand",       // 327
    "ftCo_MS_CaptureDamageMasterHand", // 328
    "ftCo_MS_CaptureWaitMasterHand",   // 329
    "ftCo_MS_ThrownMasterHand",        // 330
    "ftCo_MS_CaptureKirbyYoshi",       // 331
    "ftCo_MS_KirbyYoshiEgg",           // 332
    "ftCo_MS_CaptureLeadead",          // 333
    "ftCo_MS_CaptureLikelike",         // 334
    "ftCo_MS_DownReflect",             // 335
    "ftCo_MS_CaptureCrazyHand",        // 336
    "ftCo_MS_CaptureDamageCrazyHand",  // 337
    "ftCo_MS_CaptureWaitCrazyHand",    // 338
    "ftCo_MS_ThrownCrazyHand",         // 339
    "ftCo_MS_Barrel",                  // 340
];
