[package]
name = "ft-captain"
description = "Captain Falcon character data and callbacks (ftCaptain)"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
melee-types = { path = "../melee-types" }
melee-ft = { path = "../melee-ft" }
hsd-archive = { path = "../hsd-archive" }
gekko-math = { path = "../gekko-math" }
melee-ef = { path = "../melee-ef" }
melee-lb = { path = "../melee-lb" }
hsd-types = { path = "../hsd-types" }
melee-mp = { path = "../melee-mp" }

[dev-dependencies]
melee-test-support = { path = "../melee-test-support" }
