[package]
name = "ft-captain"
description = "Captain Falcon character data and callbacks (ftCaptain)"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
melee-types = { path = "../melee-types" }
melee-ft = { path = "../melee-ft" }
hsd-archive = { path = "../hsd-archive" }
