[package]
name = "ft-captain"
description = "Captain Falcon character data and callbacks (ftCaptain)"
version.workspace = true
edition.workspace = true

[dependencies]
ft-captain-family = { path = "../ft-captain-family" }
melee-types = { path = "../melee-types" }
melee-ft = { path = "../melee-ft" }
hsd-archive = { path = "../hsd-archive" }
gekko-math = { path = "../gekko-math" }

[dev-dependencies]
melee-test-support = { path = "../melee-test-support" }
