[package]
name = "ft-falco"
description = "Falco character data and callbacks (ftFalco)"
version.workspace = true
edition.workspace = true

[dependencies]
melee-it = { path = "../melee-it" }
ft-fox-family = { path = "../ft-fox-family" }
melee-types = { path = "../melee-types" }
melee-ft = { path = "../melee-ft" }
hsd-types = { path = "../hsd-types" }
hsd-archive = { path = "../hsd-archive" }
gekko-math = { path = "../gekko-math" }

[dev-dependencies]
melee-test-support = { path = "../melee-test-support" }
