"""Measure which Dolphin input floats produce each game pad value.

    cd harness && uv run python calibrate_pads.py [--check]

Dolphin maps an overridden stick float f to a wire byte with
llround(127 f + 128) (ControllerEmu::MapFloat); the game's SI/PAD/HSD layers
then turn that byte into HSD_PadStatus.stickX etc. Rather than model that chain,
this records a dense sweep from a savestate, reads the resulting HSD values from
the tick trace, and writes `dolphin/pad_calibration.json`:

    {"stick": {"-80": f, ..., "80": f}, "trigger": {"0": f, ..., "140": f}}

where each f is the middle of the measured float interval yielding that value.
The corpus bridge (`replay_to_scenario.py`) uses it to drive Dolphin with the
exact pad values a port recording consumed; every bridged run then verifies the
recorded pads against the recording, so a stale table cannot pass silently.
Main stick X and C-stick Y are swept together with the left trigger; the other
axes use the same Dolphin mapping (checked by `--check` on the Y/X axes).
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

import trace_io

HERE = Path(__file__).resolve().parent
OUT = HERE / "dolphin" / "pad_calibration.json"
SAVESTATE = "harness/roms/idle_fd_marth4.sav"
FIRST_FRAME = 20
STICK_SPAN, STICK_STEP = 0.66, 1 / 1024
TRIGGER_SPAN, TRIGGER_STEP = 0.60, 1 / 2048


def sweep_points() -> list[tuple[float, float]]:
    """(stick float, trigger float) per VI frame."""
    stick_n = int(2 * STICK_SPAN / STICK_STEP) + 1
    trigger_n = int(TRIGGER_SPAN / TRIGGER_STEP) + 1
    n = max(stick_n, trigger_n)
    return [(-STICK_SPAN + min(i, stick_n - 1) * STICK_STEP, min(i, trigger_n - 1) * TRIGGER_STEP)
            for i in range(n)]


def write_scenario(name: str, axes: tuple[str, str], points) -> Path:
    steps = "\n".join(
        f"  {{ frame = {FIRST_FRAME + i}, port = 0, buttons = {{ {axes[0]} = {s!r}, {axes[1]} = {s!r}, "
        f"TriggerLeft = {t!r} }} }},"
        for i, (s, t) in enumerate(points))
    path = HERE / "scenarios" / f"{name}.toml"
    path.write_text(f'''# Generated by calibrate_pads.py; safe to delete.
name = "{name}"
savestate = "{SAVESTATE}"
frames = {FIRST_FRAME + len(points) + 10}
seed = 1
stage = "FinalDestination"
inputs = [
{steps}
]

[[fighters]]
slot = 0
kind = "Marth"
controller = "scripted"

[[fighters]]
slot = 1
kind = "Fox"
controller = "scripted"
''')
    return path


def record(path: Path) -> list[dict]:
    subprocess.run([sys.executable, str(HERE / "dolphin/run_scenario.py"), str(path), "--tick-trace",
                    "--ports", "2"], check=True, stdout=subprocess.DEVNULL)
    name = path.stem
    trace = HERE / "traces" / f"{name}.tick.expected.jsonl"
    with trace_io.open_text(trace) as lines:
        return [json.loads(line) for line in lines]


def pads_by_input_frame(rows: list[dict]) -> dict[int, dict]:
    """A step issued at VI frame f is first visible in the record whose vi_frame is f + 1."""
    by_vi: dict[int, dict] = {}
    for row in rows:
        by_vi.setdefault(row["vi_frame"], row["inputs"]["p0"])
    return {vi - 1: pads for vi, pads in by_vi.items()}


def intervals(samples: list[tuple[float, int]]) -> dict[int, float]:
    spans: dict[int, list[float]] = {}
    for value, result in samples:
        spans.setdefault(result, []).append(value)
    return {k: (min(v) + max(v)) / 2 for k, v in sorted(spans.items())}


def calibrate() -> dict:
    points = sweep_points()
    path = write_scenario("zzcal_pads_x", ("StickX", "CStickY"), points)
    try:
        pads = pads_by_input_frame(record(path))
    finally:
        path.unlink(missing_ok=True)
    stick, cstick, trigger = [], [], []
    for i, (s, t) in enumerate(points):
        p = pads.get(FIRST_FRAME + i)
        if p is None:
            continue
        stick.append((s, p["stickX"]["v"]))
        cstick.append((s, p["subStickY"]["v"]))
        trigger.append((t, p["analogL"]["v"]))
    table = {"stick": intervals(stick), "cstick": intervals(cstick), "trigger": intervals(trigger)}
    for axis, lo, hi in (("stick", -80, 80), ("cstick", -80, 80), ("trigger", 0, 140)):
        missing = [v for v in range(lo, hi + 1) if v not in table[axis]]
        if missing:
            raise SystemExit(f"{axis}: no measured float yields {missing}")
    if table["stick"] != table["cstick"]:
        raise SystemExit("main and C stick mappings differ; extend the table per axis")
    return {"stick": {str(k): v for k, v in table["stick"].items() if -80 <= k <= 80},
            "trigger": {str(k): v for k, v in table["trigger"].items() if 0 <= k <= 140}}


def check(table: dict) -> None:
    """Replay every table entry on the other axes (StickY, CStickX, TriggerRight)."""
    stick = sorted((int(k), f) for k, f in table["stick"].items())
    trig = sorted((int(k), f) for k, f in table["trigger"].items())
    n = max(len(stick), len(trig))
    # Hold each entry three frames and read the middle one: lag frames drop a record.
    points = [(stick[min(i // 3, len(stick) - 1)][1], trig[min(i // 3, len(trig) - 1)][1])
              for i in range(3 * n)]
    path = write_scenario("zzcal_pads_y", ("StickY", "CStickX"), points)
    text = path.read_text().replace("TriggerLeft", "TriggerRight")
    path.write_text(text)
    try:
        pads = pads_by_input_frame(record(path))
    finally:
        path.unlink(missing_ok=True)
    bad = []
    for i in range(n):
        p = pads.get(FIRST_FRAME + 3 * i + 1) or pads.get(FIRST_FRAME + 3 * i + 2)
        if p is None:
            bad.append((i, "no record", None))
            continue
        want_s, want_t = stick[min(i, len(stick) - 1)][0], trig[min(i, len(trig) - 1)][0]
        got = (p["stickY"]["v"], p["subStickX"]["v"], p["analogR"]["v"])
        if got != (want_s, want_s, want_t):
            bad.append((i, (want_s, want_s, want_t), got))
    if bad:
        raise SystemExit(f"{len(bad)} calibration entries do not reproduce: {bad[:5]}")
    print(f"check: {n} entries reproduce on StickY/CStickX/TriggerRight")


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="only verify the existing table")
    a = ap.parse_args(argv)
    if not a.check:
        table = calibrate()
        OUT.write_text(json.dumps(table, indent=1) + "\n")
        print(f"wrote {OUT.relative_to(HERE)}: {len(table['stick'])} stick, {len(table['trigger'])} trigger values")
    check(json.loads(OUT.read_text()))


if __name__ == "__main__":
    main()
