"""Generate the tracer's ItemKind names: python harness/gen_item_kinds.py [--check]."""
from __future__ import annotations

import argparse
from pathlib import Path
import re

import data_root

HERE = Path(__file__).resolve().parent
SOURCE = data_root.DECOMP / "src/melee/it/forward.h"
OUTPUT = HERE / "item_kinds.py"


def generate(source: str) -> str:
    source = re.sub(r"/\*.*?\*/|//[^\n]*", "", source, flags=re.S)
    body = re.search(r"typedef enum ItemKind\s*\{(.*?)\}\s*ItemKind;", source, re.S)
    if body is None:
        raise ValueError("ItemKind enum not found")
    values, names = {}, {}
    value = -1
    for entry in body[1].split(","):
        if not entry.strip():
            continue
        match = re.fullmatch(r"\s*(\w+)\s*(?:=\s*(-?\w+)\s*)?", entry)
        if match is None:
            raise ValueError(f"unsupported ItemKind entry: {entry!r}")
        name, explicit = match.groups()
        value = (values[explicit] if explicit in values else int(explicit, 0)) if explicit else value + 1
        values[name] = value
        names[value] = name  # concrete aliases follow Start/Terminate sentinels
    lines = ['"""Generated by harness/gen_item_kinds.py from melee/it/forward.h; do not edit."""',
             "", "ITEM_KIND_NAMES = {"]
    lines.extend(f'    {value}: "{name}",' for value, name in sorted(names.items()))
    return "\n".join([*lines, "}", ""])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generate(SOURCE.read_text())
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            print("FAIL: regenerate harness/item_kinds.py")
            return 1
        print("PASS: ItemKind table matches it/forward.h")
    else:
        OUTPUT.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
