[package]
name = "it-gamewatch"
description = "Mr. Game & Watch's articles (it/kinds/itgamewatch*.c)"
version.workspace = true
edition.workspace = true

[dependencies]
melee-it = { path = "../melee-it" }
melee-types = { path = "../melee-types" }
melee-mp = { path = "../melee-mp" }
hsd-types = { path = "../hsd-types" }
gekko-math = { path = "../gekko-math" }
