[package]
name = "it-peach"
description = "Peach's articles: parasol, Toad and Toad's spores"
version.workspace = true
edition.workspace = true

[dependencies]
melee-it = { path = "../melee-it" }
melee-types = { path = "../melee-types" }
hsd-types = { path = "../hsd-types" }
gekko-math = { path = "../gekko-math" }
