[package]
name = "ft-peach"
description = "Peach character data and callbacks (ftPeach)"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
melee-types = { path = "../melee-types" }
melee-ft = { path = "../melee-ft" }
hsd-types = { path = "../hsd-types" }
hsd-archive = { path = "../hsd-archive" }
